local tex = require("_tex")
return {
	-- Examples of Greek letter snippets, autotriggered for efficiency
	s({ trig = ";a", snippetType = "autosnippet" }, { t("\\alpha") },{condition = tex.in_mathzone}),
	s({ trig = ";b", snippetType = "autosnippet" }, { t("\\beta") },{condition = tex.in_mathzone}),
	s({ trig = ";c", snippetType = "autosnippet" }, { t("\\varsigma") },{condition = tex.in_mathzone}),
	s({ trig = ";d", snippetType = "autosnippet" }, { t("\\delta") },{condition = tex.in_mathzone}),
	s({ trig = ";e", snippetType = "autosnippet" }, { t("\\varepsilon") },{condition = tex.in_mathzone}),
	s({ trig = ";f", snippetType = "autosnippet" }, { t("\\varphi") },{condition = tex.in_mathzone}),
	s({ trig = ";g", snippetType = "autosnippet" }, { t("\\gamma") },{condition = tex.in_mathzone}),
	s({ trig = ";h", snippetType = "autosnippet" }, { t("\\eta") },{condition = tex.in_mathzone}),
	s({ trig = ";i", snippetType = "autosnippet" }, { t("\\iota") },{condition = tex.in_mathzone}),
	s({ trig = ";j", snippetType = "autosnippet" }, { t("\\theta") },{condition = tex.in_mathzone}),
	s({ trig = ";k", snippetType = "autosnippet" }, { t("\\kappa") },{condition = tex.in_mathzone}),
	s({ trig = ";l", snippetType = "autosnippet" }, { t("\\lambda") },{condition = tex.in_mathzone}),
	s({ trig = ";m", snippetType = "autosnippet" }, { t("\\mu") },{condition = tex.in_mathzone}),
	s({ trig = ";n", snippetType = "autosnippet" }, { t("\\nu") },{condition = tex.in_mathzone}),
	s({ trig = ";o", snippetType = "autosnippet" }, { t("\\omicron") },{condition = tex.in_mathzone}),
	s({ trig = ";p", snippetType = "autosnippet" }, { t("\\pi") },{condition = tex.in_mathzone}),
	s({ trig = ";q", snippetType = "autosnippet" }, { t("\\chi") },{condition = tex.in_mathzone}),
	s({ trig = ";r", snippetType = "autosnippet" }, { t("\\rho") },{condition = tex.in_mathzone}),
	s({ trig = ";s", snippetType = "autosnippet" }, { t("\\sigma") },{condition = tex.in_mathzone}),
	s({ trig = ";t", snippetType = "autosnippet" }, { t("\\tau") },{condition = tex.in_mathzone}),
	s({ trig = ";u", snippetType = "autosnippet" }, { t("\\upsilon") },{condition = tex.in_mathzone}),
	s({ trig = ";v", snippetType = "autosnippet" }, { t("\\phi") },{condition = tex.in_mathzone}),
	s({ trig = ";w", snippetType = "autosnippet" }, { t("\\omega") },{condition = tex.in_mathzone}),
	s({ trig = ";x", snippetType = "autosnippet" }, { t("\\xi") },{condition = tex.in_mathzone}),
	s({ trig = ";y", snippetType = "autosnippet" }, { t("\\psi") },{condition = tex.in_mathzone}),
	s({ trig = ";z", snippetType = "autosnippet" }, { t("\\zeta") },{condition = tex.in_mathzone}),

	s({ trig = ";A", snippetType = "autosnippet" }, { t("\\Alpha") },{condition = tex.in_mathzone}),
	s({ trig = ";B", snippetType = "autosnippet" }, { t("\\Beta") },{condition = tex.in_mathzone}),
	s({ trig = ";C", snippetType = "autosnippet" }, { t("\\Sigma") },{condition = tex.in_mathzone}),
	s({ trig = ";D", snippetType = "autosnippet" }, { t("\\Delta") },{condition = tex.in_mathzone}),
	s({ trig = ";E", snippetType = "autosnippet" }, { t("\\Epsilon") },{condition = tex.in_mathzone}),
	s({ trig = ";F", snippetType = "autosnippet" }, { t("\\Phi") },{condition = tex.in_mathzone}),
	s({ trig = ";G", snippetType = "autosnippet" }, { t("\\Gamma") },{condition = tex.in_mathzone}),
	s({ trig = ";H", snippetType = "autosnippet" }, { t("\\Eta") },{condition = tex.in_mathzone}),
	s({ trig = ";I", snippetType = "autosnippet" }, { t("\\Iota") },{condition = tex.in_mathzone}),
	s({ trig = ";J", snippetType = "autosnippet" }, { t("\\Theta") },{condition = tex.in_mathzone}),
	s({ trig = ";K", snippetType = "autosnippet" }, { t("\\Kappa") },{condition = tex.in_mathzone}),
	s({ trig = ";L", snippetType = "autosnippet" }, { t("\\Lambda") },{condition = tex.in_mathzone}),
	s({ trig = ";M", snippetType = "autosnippet" }, { t("\\Mu") },{condition = tex.in_mathzone}),
	s({ trig = ";N", snippetType = "autosnippet" }, { t("\\Nu") },{condition = tex.in_mathzone}),
	s({ trig = ";O", snippetType = "autosnippet" }, { t("\\Omicron") },{condition = tex.in_mathzone}),
	s({ trig = ";P", snippetType = "autosnippet" }, { t("\\Pi") },{condition = tex.in_mathzone}),
	s({ trig = ";Q", snippetType = "autosnippet" }, { t("\\Chi") },{condition = tex.in_mathzone}),
	s({ trig = ";R", snippetType = "autosnippet" }, { t("\\Rho") },{condition = tex.in_mathzone}),
	s({ trig = ";S", snippetType = "autosnippet" }, { t("\\Sigma") },{condition = tex.in_mathzone}),
	s({ trig = ";T", snippetType = "autosnippet" }, { t("\\Tau") },{condition = tex.in_mathzone}),
	s({ trig = ";U", snippetType = "autosnippet" }, { t("\\Upsilon") },{condition = tex.in_mathzone}),
	s({ trig = ";V", snippetType = "autosnippet" }, { t("\\Phi") },{condition = tex.in_mathzone}),
	s({ trig = ";W", snippetType = "autosnippet" }, { t("\\Omega") },{condition = tex.in_mathzone}),
	s({ trig = ";X", snippetType = "autosnippet" }, { t("\\Xi") },{condition = tex.in_mathzone}),
	s({ trig = ";Y", snippetType = "autosnippet" }, { t("\\Psi") },{condition = tex.in_mathzone}),
	s({ trig = ";Z", snippetType = "autosnippet" }, { t("\\Zeta") },{condition = tex.in_mathzone}),


	s({ trig = "AA", snippetType = "autosnippet" }, { t("\\mathbb{A}") }, {condition = tex.in_mathzone} ),
	s({ trig = "BB", snippetType = "autosnippet" }, { t("\\mathbb{B}") }, {condition = tex.in_mathzone} ),
	s({ trig = "CC", snippetType = "autosnippet" }, { t("\\mathbb{C}") }, {condition = tex.in_mathzone} ),
	s({ trig = "DD", snippetType = "autosnippet" }, { t("\\mathbb{D}") }, {condition = tex.in_mathzone} ),
	s({ trig = "EE", snippetType = "autosnippet" }, { t("\\mathbb{E}") }, {condition = tex.in_mathzone} ),
	s({ trig = "FF", snippetType = "autosnippet" }, { t("\\mathbb{F}") }, {condition = tex.in_mathzone} ),
	s({ trig = "GG", snippetType = "autosnippet" }, { t("\\mathbb{G}") }, {condition = tex.in_mathzone} ),
	s({ trig = "HH", snippetType = "autosnippet" }, { t("\\mathbb{H}") }, {condition = tex.in_mathzone} ),
	s({ trig = "II", snippetType = "autosnippet" }, { t("\\mathbb{I}") }, {condition = tex.in_mathzone} ),
	s({ trig = "JJ", snippetType = "autosnippet" }, { t("\\mathbb{J}") }, {condition = tex.in_mathzone} ),
	s({ trig = "KK", snippetType = "autosnippet" }, { t("\\mathbb{K}") }, {condition = tex.in_mathzone} ),
	s({ trig = "LL", snippetType = "autosnippet" }, { t("\\mathbb{L}") }, {condition = tex.in_mathzone} ),
	s({ trig = "MM", snippetType = "autosnippet" }, { t("\\mathbb{M}") }, {condition = tex.in_mathzone} ),
	s({ trig = "NN", snippetType = "autosnippet" }, { t("\\mathbb{N}") }, {condition = tex.in_mathzone} ),
	s({ trig = "OO", snippetType = "autosnippet" }, { t("\\mathbb{O}") }, {condition = tex.in_mathzone} ),
	s({ trig = "PP", snippetType = "autosnippet" }, { t("\\mathbb{P}") }, {condition = tex.in_mathzone} ),
	s({ trig = "QQ", snippetType = "autosnippet" }, { t("\\mathbb{Q}") }, {condition = tex.in_mathzone} ),
	s({ trig = "RR", snippetType = "autosnippet" }, { t("\\mathbb{R}") }, {condition = tex.in_mathzone} ),
	s({ trig = "SS", snippetType = "autosnippet" }, { t("\\mathbb{S}") }, {condition = tex.in_mathzone} ),
	s({ trig = "TT", snippetType = "autosnippet" }, { t("\\mathbb{T}") }, {condition = tex.in_mathzone} ),
	s({ trig = "UU", snippetType = "autosnippet" }, { t("\\mathbb{U}") }, {condition = tex.in_mathzone} ),
	s({ trig = "VV", snippetType = "autosnippet" }, { t("\\mathbb{V}") }, {condition = tex.in_mathzone} ),
	s({ trig = "WW", snippetType = "autosnippet" }, { t("\\mathbb{W}") }, {condition = tex.in_mathzone} ),
	s({ trig = "XX", snippetType = "autosnippet" }, { t("\\mathbb{X}") }, {condition = tex.in_mathzone} ),
	s({ trig = "YY", snippetType = "autosnippet" }, { t("\\mathbb{Y}") }, {condition = tex.in_mathzone} ),
	s({ trig = "ZZ", snippetType = "autosnippet" }, { t("\\mathbb{Z}") }, {condition = tex.in_mathzone} ),
}
--\alpha \beta \varsigma \delta \varepsilon \varphi \gamma \eta \iota
-- \theta \kappa \lambda \mu \nu \omicron \pi \chi \rho \sigma \tau \upsilon \phi
-- \xi \xi \psi \zeta$
--

-- $\Alpha \Beta \Sigma \Delta \Epsilon \Phi \Gamma \Eta \Iota \Theta \Kappa
-- \Lambda \Mu \Nu \Omicron \Pi \Chi \Rho \Sigma \Tau \Upsilon \Phi \Omega \Xi
-- \Psi \Zeta$}}
